[build]
  command = "npm install && npm run build"
  publish = ".next"
  
[build.environment]
  NODE_VERSION = "18"
  PRISMA_GENERATE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"